---
- name: Deploy Book App to Server
  hosts: web
  become: true
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy app files to server
      copy:
        src: ../app/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Display deployment message
      debug:
        msg: "✅ Book app deployed successfully to {{ inventory_hostname }}"
