- name: Deploy Bookstore App
  hosts: web
  become: yes
  tasks:
    - name: Copy app files to server
      synchronize:
        src: ../app/
        dest: /var/www/bookstore
        delete: yes

    - name: Restart web server
      shell: systemctl restart nginx
